name: Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          # one_of: major,minor,patch
          any_of: breaking change,enhancement,bugfix,version bump,release,chore,documentation
          repo_token: ${{ secrets.GITHUB_TOKEN }}